CREATE TABLE MEMBER (
MNO         NUMBER          CONSTRAINT MEMBER_MNO_PK PRIMARY KEY,
MNAME       VARCHAR2(20)    NOT NULL,
EMAIL       VARCHAR2(30)    CONSTRAINT MEMBER_EMAIL UNIQUE,
PASSWORD    VARCHAR2(20)    NOT NULL,
CRE_DATE    DATE            NOT NULL
);

--DROP TABLE MEMBER;

SELECT  *
FROM    MEMBER;

DESC    MEMBER;

CREATE TABLE BOARD (
NO          NUMBER          CONSTRAINT BOARD_NO_PK PRIMARY KEY,
TITLE       VARCHAR2(50)    NOT NULL,
CONTENT     VARCHAR2(500)   NOT NULL,
MNO         NUMBER          CONSTRAINT BOARD_WRITER_FK REFERENCES MEMBER(MNO) NOT NULL,
CRE_DATE    DATE            NOT NULL,
MOD_DATE    DATE
);

--DROP TABLE BOARD;

SELECT  *
FROM    BOARD;

DESC    BOARD;

SELECT  MNO, MNAME, EMAIL, PASSWORD
FROM    MEMBER
WHERE   EMAIL = ''
AND     PASSWORD = '';

CREATE SEQUENCE MEMBER_MNO_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO MEMBER
(MNO, EMAIL, PASSWORD, MNAME, CRE_DATE)
VALUES(MEMBER_MNO_SEQ.NEXTVAL, 'S1@TEST.COM', '1111'
, '홍길동', SYSDATE);

CREATE SEQUENCE BOARD__NO_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO BOARD
(NO, TITLE, CONTENT, MNO, CRE_DATE, MOD_DATE)
VALUES(BOARD__NO_SEQ.NEXTVAL, '첫번째게시글제목', '첫번째 게시글 내용'
, 1, SYSDATE, SYSDATE);

COMMIT;