CREATE TABLE MEMBER (
MNO         NUMBER          CONSTRAINT MEMBER_MNO_PK PRIMARY KEY,
MNAME       VARCHAR2(20)    NOT NULL,
EMAIL       VARCHAR2(30)    CONSTRAINT MEMBER_EMAIL UNIQUE,
PASSWORD    VARCHAR2(20)    NOT NULL,
CRE_DATE    DATE            NOT NULL
);

SELECT  *
FROM    MEMBER;

DESC    MEMBER;

CREATE TABLE BOARD (
NO          NUMBER          CONSTRAINT BOARD_NO_PK PRIMARY KEY,
TITLE       VARCHAR2(50)    NOT NULL,
CONTENT     VARCHAR2(500)   NOT NULL,
MNO         NUMBER          CONSTRAINT BOARD_WRITER_FK REFERENCES MEMBER(MNO) NOT NULL,
CRE_DATE    DATE            NOT NULL,
MOD_DATE    DATE
);

SELECT  *
FROM    BOARD;

DESC    BOARD;